<?php

use Resume\App;

final class TestApp extends \Resume\TestCase
{
	/** @var App $app */
	private $app;
	
	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		
		$this->app = $this->factory->get("App");
	}
	
	public function testExists()
	{
		$this->assertTrue(class_exists("\\Resume\\App"));
	}
	
	public function testDeletesBuildTree()
	{
		$this->app->compile();
		
		$this->stubFilesystem->assertMethodCalledWith(
			"deleteTree",
			"build"
		);
	}
	
	public function testCompilesLess()
	{
		$this->app->compile();
		
		$this->stubLess->assertMethodCalledWith(
			"compileFile",
			BASEDIR . "/less/style.less"
		);
	}
	
	public function testWritesCssFile()
	{
		$this->stubLess->setReturnValue("compileFile", "compiled_css");
		
		$this->app->compile();
		
		$this->stubFilesystem->assertMethodCalledWith(
			"fileForceContents",
			BASEDIR . "/build/style.css",
			"compiled_css"
		);
	}
	
	public function testGetsYaml()
	{
		$this->app->compile();
		
		$this->stubFilesystem->assertMethodCalledWith(
			"getFile",
			BASEDIR . "/resume.yaml"
		);
	}
}
